# Generated by Django 5.1.2 on 2024-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
    ]
